### ISSUE TITLE
Please, where are new releases?

### ISSUE THREAD

**Issue by jack-y** [srevinsaju/Thunderbird-AppImage#10]
I use thunderbird only with appimage version, and it's great.
It seems that there is no new stable release since Feb 22. Maybe there's an issue with the continuous integration?
Please, do you plan to publish the latest release?

**Comment by BeneM32** [comment]
There is a bug in the pipline, therefore the creation of the appimage does not work anymore. After waiting for some time, I made a "mage request". Unfortunately this was not handled. Also an email from me was ignored. Therefore I have made a new pipiline. https://github.com/BeneM32/Thunderbird-AppImage

**Comment by jack-y** [comment]
Oh, what a quick and fantastic response!
Thank you so much. Great job!

**Comment by srevinsaju** [comment]
Thanks @BeneM32 for the patch, I totally missed your PR. Merged it to master,
