### ISSUE TITLE
AppImage needs updating

### ISSUE THREAD

**Issue by luisnabais** [srevinsaju/Thunderbird-AppImage#11]
Hello.
This AppImage is not being updated, it's still stuck in very old versions, for all releases (stable, beta and nightly) Latest update was on February 2022.
Can you please update this?

Thank you.

**Comment by Archargelod** [comment]
I've fixed Stable and Beta appimages, unfortunately can't find the nightly build on the official site. 
I've submitted pull request, but until it is merged, you can find fresh releases here: [my fork](https://github.com/Archargelod/Thunderbird-AppImage/releases)
