### ISSUE TITLE
TB 78 multi-profile version and I would like to use your TB 91 appImage

### ISSUE THREAD

**Issue by HDInfautre** [srevinsaju/Thunderbird-AppImage#4]
Hello
I have the TB 78 multi-profile version and I would like to use your TB 91 appImage
1/ Is it possible to switch from a .deb version to appImage with a version change ?
2/ Does your appImage support multiprofiles?
Regards

**Comment by srevinsaju** [comment]
1) Yes

2) Well... You can do this:
```bash
❯ thunderbird-appimage --help
/tmp/.mount_thundelULEo9
Usage: /tmp/.mount_thundelULEo9/thunderbird-bin [ options ... ] [URL]
       where options include:
       
...
  -P <profile>       Start with <profile>.
  --profile <path>   Start with profile at <path>.
```

**Comment by HDInfautre** [comment]
Hi
Thank you for your answer.
I have downloaded and authorized the appImage to run.
I can't launch the copy of my test profile (under TB78).
Here it is in terminal mode:
`rvx@ordi:/media/rvx/donnees/Com. informat./Applications-appimage$ ls
Thunderbird-91.0_20210818230426.AppImage
rvx@ordi:/media/rvx/donnees/Com. informat./Applications-appimage$thunderbird-appimage --help
thunderbird-appimage : commande introuvable
`

**Comment by srevinsaju** [comment]
@HDInfautre you will  have to do this instead:
```bash
./Thunderbird-91.0_20210818230426.AppImage --help
```

**Comment by HDInfautre** [comment]
HI @srevinsaju 
ok thanks it works but without automatic conversion tb78 to tb91!
How can I be sure that it is the same code as Mozilla's? Is the application signed?
 work in connection with mozilla ?
Regards

**Comment by srevinsaju** [comment]
no, this is not signed, nor is provided in connection with Mozilla. This is not a Mozilla-certified official appimage. Use it at your own risk. You may look at `.github/workflow/*.yml` to see how this appimage is built. No AppImages released are built locally, but, rather using scripts on GitHub CI.

**Comment by srevinsaju** [comment]
Closing this, feel free to open a new issue if the issue persists.
